# Services
services:                                         # ОПИС СЕРВІСІВ

  # MariaDB Service
  rtacademy_symfony_database:                     # назва сервіса
    image: mariadb:latest                         # основний образ та версія
    container_name: rtacademy_symfony_database    # назва контейнера
    restart: unless-stopped                       # політика перезавантажень сервіса (пока не буде зупинено)
    volumes:                                      # монтування томів (persistent storage) всередину контейнера
      - rtacademy_symfony_database_data:/var/lib/mysql
    ports:                                        # список відкритих назовні портів <hostPort>:<containerPort>
      - "127.0.0.1:3308:3306/tcp"                 # (відкрити підʼєднання на порт 3306 за межами контейнера тільки з локальної адреси IPv4 та на порт 3308 за протоколом TCP)
    environment:                                  # змінні оточення
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secretpassword
      MYSQL_DATABASE: blog_symfony
      MYSQL_USER: rtacademy_symfony
      MYSQL_PASSWORD: rtacademy_symfony
    networks:                                     # локальна мережа контейнера
      - rtacademy_symfony_network

  # PHP-FPM Service
  rtacademy_symfony_app:                          # назва сервіса
    build:                                        # опції збирання
      context: ./rtacademy_symfony_app            # директорія для збірки (source directory)
    image: rtacademy_symfony_app:latest           # основний образ та версія
    container_name: rtacademy_symfony_app         # назва контейнера
    restart: unless-stopped                       # політика перезавантажень сервіса (допоки не буде зупинено)
    working_dir: /var/www                         # робоча директорія
    volumes:                                      # монтування томів (persistent storage) всередину контейнера
      - ./symfony_blog:/var/www:rw                # тут необхідно в лівому аргументі (до двокрапки) вказати коректний шлях до ваших файлів
    depends_on:                                   # цей сервіс залежить від наступних сервісів
      - rtacademy_symfony_database
    networks:                                     # локальна мережа контейнера
      - rtacademy_symfony_network

  # Nginx Service
  rtacademy_symfony_web:                          # назва сервіса
    image: nginx:latest                           # основний образ та версія
    container_name: rtacademy_symfony_web         # назва контейнера
    restart: unless-stopped                       # політика перезавантажень сервіса (допоки не буде зупинено)
    working_dir: /var/www                         # робоча директорія
    volumes:                                      # монтування томів (persistent storage) всередину контейнера
      - ./symfony_blog:/var/www:ro                # тут необхідно в лівому аргументі (до двокрапки) вказати коректний шлях до ваших файлів
      - ./rtacademy_symfony_web/etc/nginx/conf.d:/etc/nginx/conf.d    # налаштування веб-сервера nginx
    ports:                                        # список відкритих назовні портів <hostPort>:<containerPort>
      - "0.0.0.0:8888:80/tcp"                     # (відкрити підʼєднання на порт 80 за межами контейнера з будь-якої адреси IPv4 та на порт 8888 за протоколом TCP)
    depends_on:                                   # цей сервіс залежить від наступних сервісів
      - rtacademy_symfony_database
      - rtacademy_symfony_app
    networks:                                     # локальна мережа контейнера
      - rtacademy_symfony_network

# Networks
networks:                                         # ОПИС МЕРЕЖ
  rtacademy_symfony_network:
    name: rtacademy_symfony_network               # назва мережі
    driver: bridge                                # тип підʼєднання (default)

# Volumes
volumes:                                          # ОПИС ТОМІВ
  rtacademy_symfony_database_data:
    name: rtacademy_symfony_database_data         # назва тому
